[package]
name = "web-serial-adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.174"
serde = { version = "1.0.219" , features = ["derive"]}
serde_json = "1.0.140"
serialport = "4.7.2"

[lib]
crate-type = ["cdylib"]
